### ISSUE TITLE
:bug:  《用 TypeScript 来写 Vue！》这篇有个小错误

### ISSUE THREAD

**Issue by sansx** [daief/daief.github.io#1]
最近在看博主的ts的文章，写的很好。
在`使用 vue-property-decorator`
这一小节中展示的`Post.vue`的代码：
```
  // watch
  @Watch('count')
  onCountChange(val: number, old: number) {
    console.log(`new value: ${val}, old value: ${old}`)
  }
```
使用了` @Watch`，但是没有从开头的`vue-property-decorator`中引入导致报错。

**Comment by daief** [comment]
谢谢你的反馈，已经进行更新！

**Comment by sansx** [comment]
不客气，我自己还有个小问题是关于vuecli的热重载的，博主的邮箱可以联系到吗，或者其他的联系方法，这个issue的问题已经解决了，所以感觉其他问题发这下面不太好，这个issue博主回复之后我就关闭。感谢。

**Comment by daief** [comment]
联系微信吧：defenghznu
